<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <AssemblyName>SimpleIoT.Gateway</AssemblyName>
    <RootNamespace>SimpleIoT.Gateway</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>YourName</Authors>
    <Description>Asynchronous IoT Data Gateway service designed for Linux containers.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.0" />
    
    </ItemGroup>

  <ItemGroup>
    <None Update="*.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>