name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # 메인 브랜치에 코드가 올라올 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Docker Build
      run: docker build -t simple-iot-gateway .